
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "ai-customer-support-lb-global-lb-frontend" {
  source                          = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v13.2.0"
  name                            = "ai-customer-support-lb-frontend-9b39"
  project_id                      = "cs-agent-trial"
  url_map_input                   = module.ai-customer-support-lb-global-lb-backend.backend_service_info
  ssl                             = true
  managed_ssl_certificate_domains = ["example.com"]
  depends_on                      = [module.project-services-cs-agent-trial, module.project-services-billing-project]
}
module "ai-customer-support-lb-global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "ai-customer-support-lb-backend-9b39"
  project_id = "cs-agent-trial"
  enable_cdn = true
  serverless_neg_backends = [{
    region          = module.ai-customer-support-frontend-service.location
    service_name    = module.ai-customer-support-frontend-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  host_path_mappings = [{"host" = "*", "path" = "/*"}]
  depends_on         = [module.project-services-cs-agent-trial, module.project-services-billing-project]
}
module "ai-customer-support-ai-agent-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.4"
  project_id                    = "cs-agent-trial"
  location                      = "us-central1"
  service_name                  = "ai-agent-service-9b39"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "env_secret_vars" = merge({"ai_customer_support_knowledge_base_db_secret_SECRET" = module.ai-customer-support-knowledge-base-db-secret.env_vars.SECRET}, {"ai_customer_support_zoho_api_keys_secret_SECRET" = module.ai-customer-support-zoho-api-keys-secret.env_vars.SECRET}), "env_vars" = {"ai_customer_support_knowledge_base_db_CLOUD_SQL_DATABASE_NAME" = module.ai-customer-support-knowledge-base-db.env_vars.CLOUD_SQL_DATABASE_NAME, "ai_customer_support_knowledge_base_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.ai-customer-support-knowledge-base-db.instance_connection_name, "ai_customer_support_knowledge_base_db_CLOUD_SQL_DATABASE_HOST" = module.ai-customer-support-knowledge-base-db.instance_first_ip_address}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/aiplatform.user"], ["roles/secretmanager.secretAccessor"])
  ingress                       = "INGRESS_TRAFFIC_ALL"
  members                       = ["allUsers"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    ai_customer_support_vertex_ai_service_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-cs-agent-trial, module.project-services-billing-project]
}
module "ai-customer-support-knowledge-base-db" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = "cs-agent-trial"
  region                      = "us-central1"
  name                        = "knowledge-base-db-9b39"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_15"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = [{
    email = module.ai-customer-support-ai-agent-service.service_account_id.email
    id    = module.ai-customer-support-ai-agent-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  depends_on = [module.project-services-cs-agent-trial, module.project-services-billing-project]
}
module "ai-customer-support-knowledge-base-db-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "cs-agent-trial"
  name        = "knowledge-base-db-secret-9b39"
  secret_data = module.ai-customer-support-knowledge-base-db.generated_user_password
  depends_on  = [module.project-services-cs-agent-trial, module.project-services-billing-project]
}
module "ai-customer-support-vertex-ai-service" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "cs-agent-trial"
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-cs-agent-trial, module.project-services-billing-project]
}
module "ai-customer-support-zoho-api-keys-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "cs-agent-trial"
  name        = "zoho-api-keys-secret-9b39"
  secret_data = "zoho-api-key-placeholder"
  depends_on  = [module.project-services-cs-agent-trial, module.project-services-billing-project]
}
module "ai-customer-support-frontend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.4"
  project_id                    = "cs-agent-trial"
  location                      = "us-central1"
  service_name                  = "ai-customer-support-frontend-service-9b39"
  containers                    = [{"container_image" = "gcr.io/cs-agent-trial/frontend-app:latest", "env_vars" = {"PROJECT_ID" = "cs-agent-trial", "LOCATION" = "global", "DIALOGFLOW_AGENT_ID" = google_dialogflow_cx_agent.customer_support_agent.name}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_ALL"
  members                       = ["allUsers"]
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-cs-agent-trial, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = "cs-agent-trial"
  location       = "global"
  service_uris   = concat(module.ai-customer-support-lb-global-lb-frontend.apphub_service_uri, module.ai-customer-support-lb-global-lb-backend.apphub_service_uri, [module.ai-customer-support-ai-agent-service.apphub_service_uri], [module.ai-customer-support-knowledge-base-db.apphub_service_uri], [module.ai-customer-support-frontend-service.apphub_service_uri])
  application_id = "ren-360-service-assistant"
}
module "project-services-cs-agent-trial" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "cs-agent-trial"
  disable_services_on_destroy = false
  activate_apis               = ["accesscontextmanager.googleapis.com", "admin.googleapis.com", "appengine.googleapis.com", "billingbudgets.googleapis.com", "certificatemanager.googleapis.com", "cloudbilling.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "essentialcontacts.googleapis.com", "iam.googleapis.com", "iamcredentials.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "oslogin.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "serviceconsumermanagement.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "sqladmin.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com", "dialogflow.googleapis.com"]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "cs-agent-trial"
  disable_services_on_destroy = false
  activate_apis               = ["accesscontextmanager.googleapis.com", "admin.googleapis.com", "appengine.googleapis.com", "apphub.googleapis.com", "billingbudgets.googleapis.com", "certificatemanager.googleapis.com", "cloudbilling.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "essentialcontacts.googleapis.com", "iam.googleapis.com", "iamcredentials.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "oslogin.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "serviceconsumermanagement.googleapis.com", "servicenetworking.googleapis.com", "serviceusage.googleapis.com", "sqladmin.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}


resource "google_dialogflow_cx_agent" "customer_support_agent" {
  display_name          = "AI Customer Support Agent"
  location              = "global"
  default_language_code = "en"
  time_zone             = "America/New_York"
  project               = "cs-agent-trial"
}

resource "google_project_iam_member" "frontend_dialogflow_client" {
  project = "cs-agent-trial"
  role    = "roles/dialogflow.client"
  member  = "serviceAccount:${module.ai-customer-support-frontend-service.service_account_id.email}"
}
