
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "ai-customer-support-lb-global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.ai-customer-support-lb-global-lb-frontend.external_ip
}
output "ai-customer-support-lb-global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.ai-customer-support-lb-global-lb-frontend.external_ipv6_address
}
output "ai-customer-support-lb-global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.ai-customer-support-lb-global-lb-frontend.ip_address_internal_managed_http
}
output "ai-customer-support-lb-global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.ai-customer-support-lb-global-lb-frontend.ip_address_internal_managed_https
}
output "ai-customer-support-ai-agent-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-customer-support-ai-agent-service.service_uri
}
output "ai-customer-support-frontend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.ai-customer-support-frontend-service.service_uri
}

output "dialogflow_agent_id" {
  value = google_dialogflow_cx_agent.customer_support_agent.name
}
